### ISSUE TITLE
Support different styles of tests using a config parameter

### ISSUE THREAD

**Issue by thatkookooguy** [Kibibit/tdd1t#38]
right now, we're looking for a string input passed to a `it` function. But we can easily make the function name a variable, and support other style of test writing like:

```javascript
test('creates a comment when an issue is opened', async () => {
  // ...
});
```

This can be done by adding a `tdd1tTestFunctionName` parameter to tdd1t `config.yml` file which will default to `it`, but can be replaced with something else. for example:
```yaml
tdd1tTestFunctionName: test
```

**Comment by ZimGil** [comment]
This issue is resolved with #50 being merged
